### ISSUE TITLE
Unexpected key(s) in state_dict using pretrained model

### ISSUE THREAD

**Issue by bakszero** [ChuanMeng/DukeNet#2]
Hi, I get the following error while trying to run inference with the pretrained model. Not sure how to resolve this, any help would be appreciated. Thanks!

```torch_version:1.4.0
CUDA_version:10.1
cudnn_version:7603
Vocabulary size 30522
The number of dev_samples: 8814
The number of test_seen_samples: 4336
The number of test_unseen_samples: 4370
Start inference at epoch d_3
Traceback (most recent call last):
  File "DukeNet/Run.py", line 321, in <module>
    inference(args)
  File "DukeNet/Run.py", line 261, in inference
    inference(args.dataset, i)
  File "DukeNet/Run.py", line 206, in inference
    model.load_state_dict(torch.load(file)["model"])
  File "/home/bakhtiyar/anaconda3/envs/dukenet-2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DukeNet:
	Missing key(s) in state_dict: "enc.enc.embeddings.position_ids", "dec.embedding.0.position_ids", "dec.embedding.0.word_embeddings.weight", "dec.embedding.0.position_embeddings.weight", "dec.embedding.0.token_type_embeddings.weight", "dec.embedding.0.LayerNorm.weight", "dec.embedding.0.LayerNorm.bias", "dec.embedding.1.pe". 
	Unexpected key(s) in state_dict: "dec.embedding.word_embeddings.weight", "dec.embedding.position_embeddings.weight", "dec.embedding.token_type_embeddings.weight", "dec.embedding.LayerNorm.weight", "dec.embedding.LayerNorm.bias". 

```

**Comment by ChuanMeng** [comment]
Now I just updated my files, and now you can try again.

**Comment by bakszero** [comment]
I get a slightly different key error with the updated files:

```Traceback (most recent call last):
  File "DukeNet/Run.py", line 321, in <module>
    inference(args)
  File "DukeNet/Run.py", line 261, in inference
    inference(args.dataset, i)
  File "DukeNet/Run.py", line 206, in inference
    model.load_state_dict(torch.load(file)["model"])
  File "/home/bakhtiyar/anaconda3/envs/dukenet-2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DukeNet:
	Missing key(s) in state_dict: "enc.enc.embeddings.position_ids", "dec.embedding.position_ids". 
```

**Comment by ChuanMeng** [comment]
I just searched it on the Internet, and I found someone also encounter this issue. That is because the version of transformers.
Please uninstall the the latest version of transformers, and try the following:
pip install transformers==2.6

Please let me know you run my code successfully : ).

**Comment by ChuanMeng** [comment]
see that:
https://discuss.huggingface.co/t/missing-keys-model-embeddings-position-ids-when-loading-model-using-state-dict/744

**Comment by bakszero** [comment]
Works now! Thanks! :smile:

**Comment by ChuanMeng** [comment]
My pleasure.
